language: java
sudo: false
jdk:
  - oraclejdk8
before_install:
  - chmod +x gradlew
script:
  - "./gradlew clean build"
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"
before_deploy:
  - openssl aes-256-cbc -K $encrypted_32089ed80b0a_key -iv $encrypted_32089ed80b0a_iv -in .travis/github_deploy_key.enc -out .ssh/github_deploy_key -d
  - mkdir -p .ssh
  - chmod -r 600 .ssh/
  - eval `ssh-agent -s`
  - ssh-add .ssh/github_deploy_key
  - export RELEASE_JAR_LIBRARY=$(ls build/libs/*.jar)
  - export GIT_TAG=v1.1-SNAPSHOT
  - echo "Deploying $RELEASE_JAR_LIBRARY to GitHub releases as $GIT_TAG"
  - git config --global user.email "builds@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git tag $GIT_TAG -a -f -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
  - git push -q https://collinsmith@github.com/collinsmith/abstract-builder-pattern --tags
deploy:
  provider: releases
  api_key:
    secure: rvvTseI53cpj0wAu+S5w+cWgaRJRqF1EwkwTVdF5FL2qVbjzqNVIjgjgXJrstGEphWmLutqwj7y2YohwSkwc0C8x0gzpFFeJhYLtZlwOJVCr3LlbDqkpDSJbatbCrC1SjU6WuoizrW8p98PjTnvQgexdM3L3Org5473Xi8EYVDsshEsWQsuD0Zw3cx/VFGOK/wmYclbAJCIjo/MnQ7Hs9G2tij+Su1asUjZMNpI/q7sW++Bq/IKeukr2mJwHmMblqwfGGZP7OTSfr3HIx1kmtGCTF8YqlQnMzNqjUQ6SVWTUje3Ldpp87BYCnaOgVkH/FGGrg1wXQ1Nxp2lBkCDu/xeIeBs3VEuDQmW+S2YvMEdZ5bNKDwtQNM67EnqWasfwwLcw9HQ1rFWxovsF97je0rCaCjiXvoK2ocv0M6f9u8X/G4ZxJagG1OKYH+FNerJgz6LFCFcm7Su1+JOwKKWzl0n+z5f8MBQCFabCw7jZiBb54gBvsSsIUZ3EZqPLKXNtFBPU1b35wh4EYJznPQ5ObuNqJyCxBrKpR1owdF9CW0x2Yws3YWtyOFeT/NTYHTb5oQrxn2HgyDmI/sk8smXXkxba9Sh/Vp62XpPhvKlOMmzq4smcFV1E4KM6AbAcjQ0v5NxGVuiNM2vMwPzlKQ6a3jo98pPs5V/Uq2NnPJahHe8=
  file_glob: true
  file: "${RELEASE_JAR_LIBRARY}"
  skip_cleanup: true
  on:
    repo: collinsmith/abstract-builder-pattern
    tags: false
    branch: master
branches:
  except:
    - /^*-v[0-9]/
env:
  global:
    secure: ERsnuLipWm3WWwf8WE0nFoRcxCXBDjBvurIoLeA6k0UnWGIRP+wxjWsxPJADZjJqWqTOQjoh6tXYwvE5LTNq3uxct5ERSrioDbeQw86jLcBdocHsFWG61gP+BV+PphbWVesRxgLO+ujo0FPpEC1l4UrjSWoCRe8xECo8TePbkVP5xwv6Y3Xd/OQWlkRhQkP7+nvwYEU7aKT2+CmdLbXqAx5sm6EzP2wcvWaZ7uwsG9fZy+Yp2iATRiY9WNKGO8uaOVRFuB0rY+US4SAJrm+cm2cP5nt7TH9oIRCtZi/jnTzikZA7zQKSRwnyd6B/2mO2nZacJ5tC4Lbgxw8UAumhBL8Ypkc6CeHza5eeMUd7ffbVShbzBAo70wMDkdw2tz9G5T/PJIcxZOd1Lew/KWE5WbysWDhUhqYEFNJqZk+uTXVhiDYWfOR9EBJao7BlgZkLj0wW0hApnLUPl0s++D2scEGQKkKFQ0aSU4uq1Ca1e7Q8jIsPkYehmES3r4pTDGKQmgpVqR1vugjoyVHVfcjo05n2bHirA9Y3cnWRF8nNygvYmW05o3d59MfKSlzWgaCbh0LH/feobqT5Wq5begirbMxzykORhRcXz/xIYZsldu3VZ1GYCpZFjtXAM22Tkn/mjGyDsCJGNn8Oi1Mo5JJIS11aY4CmATb66UZwNYEgd3g=
    secure: DGrTm4vp8PDQiageuNxmIW8BUZGDIMvkmzWWukQyUYdeH9SG2x5WlmQU3dSxLG/i7AEBL/KW6h1Z4x5RXE5rywAAhEUdlwpC9YGCHEpsFH2QnA7TTuYNrdrGNFtr73IQ0wRwmLh6Isd4R7D9AbLgcE+FX2ywFbVwRuWDzW0hGAjDa4TZwG4LoYa2Rv40DwJl/VhEEleOKMafJVNNbp6pEH+KeRWkENBePDeQMHGF3vZ3b2AwcjYYZIwxnGoUTeXntM5lUsa662ypKO6YJrSdwn17MxNQrkWBtV9Li0knoAip70JIgDKC7igRIa6Ty1mouG8SiVJDh4+R8dHsZvU2gjaTq/u0vRbj1IYegBq39s2TA0ay4W0fAxq5ozw2mRlpjQ4nf8rk6XAEiKYsuBarHqNGP6AWXxLz7RIkC/qYVXHAoFeOxBBkj6NA6AbmCRc1FDdXBMa7oGVlXYzrHnkhZ60Xh9I5Et9zR8wUoMU9/7w5dQIOVx96htie7oesGWXpOLYpUrARpdKapGPSuYRJVE36kb8bceQXydYgv+/qVCyTGOyNmmbfaOnUofLTJ1Lt2ohlFjbQpr0y0VTeh8/Jd5vfCifodR0D2V2WkIgf8kJjj0GWgTLLhIq3h2hzqHHzsUJEQc2CKgiyFysmhNV48RcgMZj5fqxHN8t7yrOeitk=