language: java
sudo: false

jdk:
  - oraclejdk8

script:
  - git update-index --chmod=+x gradlew
  - ./gradlew clean build
  
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/